name: Build Padavan Firmware

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  WORK_DIR: /home/runner/work/build-padavan
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 准备工作目录
      run: |
        echo "开始时间：$(date "+%Y-%m-%d %H:%M:%S")"
        sudo mkdir -p ${{ env.WORK_DIR }}
        sudo chown -R $USER:$USER ${{ env.WORK_DIR }}
        cd ${{ env.WORK_DIR }}
        echo "工作目录: $(pwd)"

    - name: 安装编译环境
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano \
        xxd python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        wget libc-dev-bin gcc-multilib g++-multilib libssl-dev libxml-parser-perl

    - name: 克隆源码
      working-directory: ${{ env.WORK_DIR }}
      run: |
        git clone --depth=1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} rt-n56u
        cd rt-n56u
        git submodule update --init --recursive
        echo "源码目录内容:"
        ls -la

    - name: 构建工具链
      run: |
        cd ${{ env.WORK_DIR }}/rt-n56u/toolchain
        echo "当前目录: $(pwd)"
        echo "目录内容:"
        ls -la
        chmod +x build_toolchain.sh
        sudo ./build_toolchain.sh
