name: Build Padavan Firmware

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  WORK_DIR: /home/runner/work/build-padavan
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 准备工作目录
      run: |
        echo "=== 创建工作目录 ==="
        sudo mkdir -p ${{ env.WORK_DIR }}
        sudo chown -R $USER:$USER ${{ env.WORK_DIR }}
        cd ${{ env.WORK_DIR }}
        echo "当前位置: $(pwd)"

    - name: 克隆源码
      run: |
        echo "=== 克隆主仓库 ==="
        cd ${{ env.WORK_DIR }}
        git clone --depth=1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} rt-n56u
        cd rt-n56u
        
        echo "=== 更新子模块 ==="
        git submodule init
        git submodule update
        
        echo "=== 检查目录结构 ==="
        ls -la
        
        echo "=== 手动克隆 toolchain ==="
        git clone --depth=1 https://github.com/hanwckf/padavan-toolchain.git toolchain
        
        echo "=== 检查 toolchain 目录 ==="
        ls -la toolchain/

    - name: 构建工具链
      run: |
        echo "=== 开始构建工具链 ==="
        cd ${{ env.WORK_DIR }}/rt-n56u/toolchain
        echo "当前位置: $(pwd)"
        echo "目录内容:"
        ls -la
        
        if [ -f "build_toolchain.sh" ]; then
          echo "找到构建脚本，开始编译..."
          chmod +x build_toolchain.sh
          sudo ./build_toolchain.sh
        else
          echo "错误: build_toolchain.sh 不存在!"
          exit 1
        fi
