name: Build Padavan Firmware

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
  WORK_DIR: /home/runner/work/build-padavan
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 准备工作目录
      run: |
        echo "=== 创建工作目录 ==="
        sudo mkdir -p ${{ env.WORK_DIR }}
        sudo chown -R $USER:$USER ${{ env.WORK_DIR }}
        cd ${{ env.WORK_DIR }}

    - name: 克隆源码
      run: |
        echo "=== 克隆主仓库 ==="
        cd ${{ env.WORK_DIR }}
        git clone --depth=1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} rt-n56u
        cd rt-n56u
        
        echo "=== 更新子模块 ==="
        git submodule init
        git submodule update
        
        echo "=== 准备工具链 ==="
        mkdir -p toolchain
        cd toolchain
        
        echo "=== 下载预编译工具链 ==="
        wget ${{ env.TOOLCHAIN_URL }}
        
        echo "=== 解压工具链 ==="
        tar -xf mipsel-linux-uclibc.tar.xz
        
        echo "=== 检查工具链目录 ==="
        ls -la
        
        echo "=== 创建编译脚本 ==="
        cat > build_toolchain.sh << 'EOF'
        #!/bin/bash
        
        if [ -d "mipsel-linux-uclibc" ]; then
          echo "工具链已存在，跳过编译"
          exit 0
        else
          echo "错误：工具链目录不存在！"
          exit 1
        fi
        EOF
        
        chmod +x build_toolchain.sh

    - name: 构建工具链
      run: |
        echo "=== 开始构建工具链 ==="
        cd ${{ env.WORK_DIR }}/rt-n56u/toolchain
        echo "当前位置: $(pwd)"
        echo "目录内容:"
        ls -la
        
        if [ -f "build_toolchain.sh" ]; then
          echo "执行构建脚本..."
          sudo ./build_toolchain.sh
        else
          echo "错误: build_toolchain.sh 不存在!"
          exit 1
        fi
