name: Build Padavan Firmware

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device to build'
        required: true
        default: 'dir-645_a1'
        type: choice
        options:
        - dir-645_a1

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Initialize Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano \
        xxd python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        wget libc-dev-bin gcc-multilib g++-multilib libssl-dev libxml-parser-perl \
        python3 python3-distutils python3-setuptools libtool autoconf automake gcc \
        make git device-tree-compiler

    - name: Clone Source Code
      run: |
        echo "Current directory: $(pwd)"
        git clone --depth=1 $REPO_URL
        echo "After clone, directory contents:"
        ls -la
        echo "Entering rt-n56u directory..."
        cd rt-n56u || exit 1
        echo "rt-n56u directory contents:"
        ls -la
        echo "Updating submodules..."
        git submodule update --init --recursive

    - name: Prepare Toolchain
      run: |
        echo "Current directory: $(pwd)"
        echo "Checking rt-n56u directory..."
        ls -la rt-n56u || echo "rt-n56u directory not found"
        echo "Checking toolchain directory..."
        ls -la rt-n56u/toolchain || echo "toolchain directory not found"

    - name: Build Toolchain
      run: |
        cd rt-n56u/toolchain || exit 1
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Making build_toolchain.sh executable..."
        chmod +x build_toolchain.sh
        echo "Starting toolchain build..."
        sudo ./build_toolchain.sh

    - name: Copy Config File
      if: success()
      run: |
        echo "Current directory: $(pwd)"
        cp configs/${{ github.event.inputs.device }}.config rt-n56u/trunk/.config

    - name: Build Firmware
      if: success()
      run: |
        cd rt-n56u/trunk
        sudo chmod +x ./clear_tree.sh
        sudo chmod +x ./build_firmware.sh
        sudo ./clear_tree.sh
        sudo ./build_firmware.sh

    - name: Upload Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build_logs
        path: |
          rt-n56u/trunk/*.log
        if-no-files-found: warn

    - name: Upload Firmware
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.device }}_firmware
        path: rt-n56u/trunk/images/*.trx
        if-no-files-found: error

    - name: Generate Release Tag
      id: tag
      if: success()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: rt-n56u/trunk/images/*.trx
        generate_release_notes: true
