name: 构建 DIR-645 Padavan 固件

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  WORK_DIR: /opt/rt-n56u
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 检出配置
      uses: actions/checkout@v3

    - name: 安装编译依赖
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin

    - name: 克隆源码
      run: |
        sudo mkdir -p $WORK_DIR
        sudo chown -R $USER:$USER $WORK_DIR
        git clone --depth=1 $REPO_URL $WORK_DIR
        cd $WORK_DIR
        git submodule update --init --recursive
        
        echo "源码目录内容:"
        ls -la

    - name: 准备设备配置
      run: |
        echo "创建设备配置目录..."
        mkdir -p $WORK_DIR/trunk/configs/boards/DIR-645
        
        echo "复制板级配置..."
        cp -f configs/boards/DIR-645/* $WORK_DIR/trunk/configs/boards/DIR-645/
        
        echo "复制模板配置..."
        cp -f configs/templates/dir-645.config $WORK_DIR/trunk/configs/templates/
        
        echo "检查配置文件:"
        ls -la $WORK_DIR/trunk/configs/boards/DIR-645/
        ls -la $WORK_DIR/trunk/configs/templates/dir-645.config

    - name: 准备编译
      run: |
        cd $WORK_DIR/trunk
        cp configs/templates/dir-645.config .config
        
        echo "检查编译配置:"
        ls -la .config

    - name: 开始编译
      run: |
        cd $WORK_DIR/trunk
        fakeroot ./build_firmware_modify DIR-645

    - name: 上传固件
      uses: actions/upload-artifact@v3
      with:
        name: DIR645_Padavan
        path: ${{ env.WORK_DIR }}/trunk/images/*.trx
        if-no-files-found: error

    - name: 创建发布
      uses: softprops/action-gh-release@v1
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.run_number }}
        name: DIR-645 Padavan Build-${{ github.run_number }}
        files: ${{ env.WORK_DIR }}/trunk/images/*.trx
        body: |
          ### DIR-645 A1 Padavan 固件
          
          - 编译时间：${{ env.TZ }}
          - 版本号：${{ github.run_number }}
          - 源码：[hanwckf/rt-n56u](https://github.com/hanwckf/rt-n56u)
