name: Build Padavan Firmware

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device to build'
        required: true
        default: 'dir-645_a1'
        type: choice
        options:
        - dir-645_a1

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Initialize Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano \
        xxd python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        wget libc-dev-bin gcc-multilib g++-multilib libssl-dev libxml-parser-perl \
        python3 python3-distutils python3-setuptools libtool autoconf automake gcc \
        make git device-tree-compiler

    - name: Clone Source Code
      run: |
        git clone --depth=1 $REPO_URL
        cd rt-n56u
        git submodule update --init --recursive
        echo "Checking repository structure:"
        ls -la

    - name: Build Toolchain
      run: |
        cd rt-n56u/toolchain
        sudo ./build_toolchain.sh

    - name: Copy Config File
      run: |
        cp configs/${{ github.event.inputs.device }}.config rt-n56u/trunk/.config

    - name: Build Firmware
      run: |
        cd rt-n56u/trunk
        sudo ./clear_tree.sh
        sudo ./build_firmware.sh

    - name: Upload Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build_logs
        path: |
          rt-n56u/trunk/*.log
        if-no-files-found: warn

    - name: Upload Firmware
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.device }}_firmware
        path: rt-n56u/trunk/images/*.trx
        if-no-files-found: error

    - name: Generate Release Tag
      id: tag
      if: success()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: rt-n56u/trunk/images/*.trx
        generate_release_notes: true
